name: quicktrace
description: A lightweight, colorful tracing library for Dart and Flutter with cross-platform safe colors and smart filtering capabilities.
version: 1.0.0
homepage: https://github.com/LeDuyViet/quicktrace

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - tracing
  - debugging
  - performance
  - logging
  - monitoring

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
